#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ncurses.h>
#include <signal.h>	
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <locale.h>
#include <unistd.h>
#include "texteditor.h"